WAIT_DURATION = 120 # 2 minutes

SCENARIO_MUTATION_RATE = 0.6
MUTATION_RATE = 0.7
CROSSOVER_RATE = 0.6
CROSSOVER_COMPOSITION_RATE = 0

POPULATION_INJECTION_RATE = 0
POPULATION_INJECTION_SIZE = 2

MIN_SCENARIO_MUTATION_RATE = 0.05
MAX_SCENARIO_MUTATION_RATE = 0.9
FITNESS_IMPROVEMENT_THRESHOLD = 0.01